### PR TITLE
Bumped version to work with 0.17

### PR DESCRIPTION
**Pull request by Tanoh**

### CODE REVIEW

**Comment by KvaNTy** [comment]
@Tanoh Oh. Everything still works? I haven't been paying attention to factorio for a while. Have you tested it?

**Comment by KvaNTy** [comment]
Alright, everything looks fine. Thank you.

**Comment by Tanoh** [comment]
@KvaNTy Hi, yeah I tested it quickly and it seemed to be working fine. I didn't investigate if there's a new way to do it, but the old seems to be working

**Comment by KvaNTy** [comment]
@Tanoh That's good. I was concerned if it still works as intended because I remember devs planing to overhaul UI at some point. I'm gonna update forum and mod portal pages in a couple of days once I sort out weird access issues I have when I try to login there. Anyway, thanks again for reminding me of this mod existence :)

**Comment by Tanoh** [comment]
@KvaNTy Yeah, they did a lot of changes but it seems to be working still.

And I use this mod a lot when playing Bob & Angels :smile: If you're not playing much and want, I'm willing to maintain it.

**Comment by KvaNTy** [comment]
@Tanoh Good to know. 😄 I'm definitely still planing to stick around, but I added you to collaborators in this repo just in case.

**Pull request merged**
